### ISSUE TITLE
MMI codes

### ISSUE THREAD

**Issue by scull06** [himelbrand/react-native-forward-calls#1]
Hello I want to use this package to configure forward settings, but the apparently the MMI codes are hard coded... 
How can I solve this issue 
Thanks in advance

**Comment by himelbrand** [comment]
@scull06 Hello,
is there a specific MMI code you want to use?
or would you just like to have a custom function that receives the MMI code as a param?

in any way I can make the improvment (they were planned anyway) , since this repo is still a work in progress, but I'm a student in the university and right now are my final exams for this semester so it will not happen in the next few days.

if you're in a rush I encourage you to make a pull request with the modification and contribute the new features to the repo.

in case you prefer me to add it I will get to it as soon as possible
have a nice day,
Himelbrand

**Comment by himelbrand** [comment]
added support for custom MMI codes
